version: 1.1.0

#定时保存功能 防止服务器意外崩溃导致未保存数据丢失
AutoSave:
  #是否启用
  Enable: true
  #时间 秒（不建议过小,会导致重复写入）
  Time: 600

#数据库配置
Mysql:
  Use: false
  Url: "jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT"
  User: "root"
  PassWord: "root"
  Table: "xiaoonline"